
package paquete_factura;

import java.util.ArrayList;
public class ListaProductos {
    
    ArrayList<Producto> ProductsList = new ArrayList<>();
    
    Producto p0 = new Producto(0000, "Escriba acá su producto", "unidades",0);
    Producto p1 = new Producto(0001, "  Acometida primaria XLPE 3No 11/0+ No2 cu", "ML", 14000);
    Producto p2 = new Producto(0002, "  Aisladero 1F o pararayos 1F", "UN", 75000);
    Producto p3 = new Producto(0003, "  Aisladero 3F(sin pararayos)", "UN", 142500);
    Producto p4 = new Producto(0004, "  Aisladero 3F(con pararrayos)", "UN", 230000);
    Producto p5 = new Producto(0005, "  Viento convencional o farol primario", "UN", 142500);
    Producto p6 = new Producto(0006, "  Viento convencional o farol secundario", "UN", 117000);
    Producto p7 = new Producto(0007, "  Bajante por dentro de poste", "UN", 126500);
    Producto p8 = new Producto(8,"  Bajante telefónico 2' y 3'(4.5m)zunchado,sin cables", "UN", 126500);
    Producto p9 = new Producto(9, "  Cajas de 30x30", "UN", 70500);
    Producto p10 = new Producto(10, "Bajantes secundario 2', 3' ó 4', sin cables", "UN", 126500);
    Producto p11 = new Producto(11, "Caja de energia 50x50 ó 60x60 ", "UN ", 142500);
    Producto p12 = new Producto(12, "Caja de telefonos 60x80 (una tapa) ", "UN ", 158000);
    Producto p13 = new Producto(13, "Caja de telefonos 80x120 2 tapas", "UN ", 215000);
    Producto p14 = new Producto(14, "Conos exteriores e interiores (terminal premoldeadas) ", "JG",237500);
    Producto p15 = new Producto(15, "Estribos 1F", "UN ",22800);
    Producto p16 = new Producto(16, "Linea 1o No2 - No 1/0 ACSR ", "ML",7200);
    Producto p17 = new Producto(17, "Linea 3o No4/0 a No 233 ACSR", "ML",18800);
    Producto p18 = new Producto(18, "Linea 3o No2 a No 1/0 ACRS", "ML",14000);
    Producto p19 = new Producto(19, "Linea secundaria triplex o cuadruplex", "ML",3700);
    Producto p20 = new Producto(20, "Lnstalacion de trafo 1F en poste (incluye protecciones)", "UN",406000);
    Producto p21 = new Producto(21, "instalacion de trafo 3F en poste (incluye protecciones)", "UN",462250);
    Producto p22 = new Producto(22, "energizada o desconexion de transformador", "UN",119000);
    Producto p23 = new Producto(23, "luminaria A.P Na ", "UN ",45000);
    Producto p24 = new Producto(24, "pintura franjas poste concreto (no incluye pintura)", "UN",23000 );
    Producto p25 = new Producto(25, "poste concreto 14 Mts", "UN ",239500);
    Producto p26 = new Producto(26, "poste concreto 12 Mts", "UN ",182750);
    Producto p27 = new Producto(27, "poste concreto 8 Mts ", "UN",164500);
    Producto p28 = new Producto(28, "poste de madera de 12 Mts", "UN ",166000 );
    Producto p29 = new Producto(29, "poste de madera de 10 Mts", "UN",139750);
    Producto p30 = new Producto(30, "poste de madera de 8 Mts", "UN ",107500);
    Producto p31 = new Producto(31, "reflector Na o MH 1500 W ó 400W ", "UN",43000);
    Producto p32 = new Producto(32, "retiro poste de concreto 14 Mts recortado", "UN",219300);
    Producto p33 = new Producto(33, "retiro poste de concreto 12 Mts recortado", "UN",156950);
    Producto p34 = new Producto(34, "retiro poste de concreto 8 Mts recortado", "UN",123000);
    Producto p35 = new Producto(35, "retiro poste de concreto 14 Mts escabado", "UN",174150);
    Producto p36 = new Producto(36, "retiro poste de concreto 12 Mts escabado", "UN",157000 );
    Producto p37 = new Producto(37, "retiro poste de concreto 8 Mts escabado", "UN",139750);
    Producto p38 = new Producto(38, "retiro poste de madera 8 Mts", "UN",75000);
    Producto p39 = new Producto(39, "retiro de neopreno", "ML",1200);
    Producto p40 = new Producto(40, "retiro de linea trifasica", "UN",8000 );
    Producto p41 = new Producto(41, "retiro de linea monofasica", "UN",5000);
    Producto p42 = new Producto(42, "retiro de cuadruplex", "UN",2700);
    Producto p43 = new Producto(43, "retiro de triplex", "UN",2700);
    Producto p44 = new Producto(44, "retiro de vestidas trifasicas", "UN",100000);
    Producto p45 = new Producto(45, "retiro de vestidas monofasicas", "UN",59000);
    Producto p46 = new Producto(46, "retiro de vestidas secundarias", "UN",13500);
    Producto p47 = new Producto(47, "retiro de transformador monofasico", "UN",252000);
    Producto p48 = new Producto(48, "retiro de transformador trifasico", "UN",302000);
    Producto p49 = new Producto(49, "traslado poste de concreto 14 Mts", "UN",413000);
    Producto p50 = new Producto(50, "traslado poste de concreto 12 Mts", "UN",338600);
    Producto p51 = new Producto(51, "traslado poste de concreto 8 Mts ", "UN",293000);
    Producto p52 = new Producto(52, "puesta a tierra (mejoramiento triangulo)", "UN",146200);
    Producto p53 = new Producto(53, "vestida secundaria", "UN",20500);
    Producto p54 = new Producto(54, "vestida 1F primaria", "UN",71000);
    Producto p55 = new Producto(55, "vestida 3F primaria", "UN",253700);
    Producto p56 = new Producto(56, "vestira para acometida primaria RA2-017", "UN",237000);
    Producto p57 = new Producto(57, "instalacion de contador en poste (incluye caja, contador y proteccion)", "UN",174000);
    Producto p58 = new Producto(58, "instalacion de cable encauchetado", "ml",2500);
    Producto p59 = new Producto(59, "instalacion de gabinete de medida provisional (incluye gabinete y bajante)", "UN",205000);
    Producto p60 = new Producto(60, "retiro de gabinete y bajante y provisional", "UN",168000);
    Producto p61 = new Producto(61, "Instalacion de breque industrial en gavinete", "UN",49000 );
    Producto p62 = new Producto(62, "Instalacion de breque industrial en CAJA", "UN",65500 );
    Producto p63 = new Producto(63, "Instalación de tablero provisional", "UN",50000);
    Producto p64 = new Producto(64, "Instalación de ducto de 1\"  ó  2\"  RVC ", "mt",2300);
    Producto p65 = new Producto(65, "INSTALACION DE DUCTO   DE 3\"   O   4\" ", "MT",2700);
    Producto p66 = new Producto(66, "INSTALACION  DE  ACOMETIDA  EN   2 N°  1/0  +  N°  2 ", "MT",5000);
    Producto p67 = new Producto(67, "INSTALACION  DE   ACOMETIDA  EN  2  N°  2/0  + 1  N°  1/0 ", "MT",5300);
    Producto p68 = new Producto(68, "INSTALACION DE ACOMETIDA 2  N° 4/0 + 1 N° 2/0 ", "MT",5600);
    Producto p69 = new Producto(69, "INSTALACION  DE   ACOMETIDA  EN  3  N°  10 ", "MT",2600);
    Producto p70 = new Producto(70, "INSTALACION  DE  ACOMETIDA  EN  2  N°  2  +N°  4 ", "MT",3800);
    Producto p71 = new Producto(71, "INSTALACION  DE  CAJAS  DE  CONTADOR  DOBLE ", "UN ",79500);
    Producto p72 = new Producto(72, "INSTALACION  DE  CONTADOR   ", "UN",91500 );
    Producto p73 = new Producto(73, "retiro de acometida  primaria en x l p", "ml",7100);
    Producto p74 = new Producto(74, "retiro de aisladero  1f  ó pararrayo", "UN",32500);
    Producto p75 = new Producto(75, "retiro de aisladero 3f sin pararrayos", "UN",63500);
    Producto p76 = new Producto(76, "retiro de aisladero  3f con  pararrayos ", "UN",112000);
    Producto p77 = new Producto(77, "RETIRO DE BAJANTE  TELEFONICO DE 2\" 3\" O 4\" ", "UN",48000);
    Producto p78 = new Producto(78, "RETIRO DE BAJANTE SECUNDARIO DE 2\" 3\" O 4\" SIN  CABLES ", "UN",66000);
    Producto p79 = new Producto(79, "RETIRO DE LUMINARIA DE A P  NA", "UN",32000);
    Producto p80 = new Producto(80, "RETIRO DE REFLETORES", "UN",28500);
    Producto p81 = new Producto(81, "INCSTALACION DE NEOPRENO ", "ML",2400);
    Producto p82 = new Producto(82, "PUESTA A TIERRA NORMAL", "UN",59000);
    Producto p83 = new Producto(83, "RETIRO DE  VESTIDA  PARA  ACOMETIDA PRIMARIA ", "UN",110000);
    Producto p84 = new Producto(84, "RETIRO DE  ENCAUCHETADO", "ML",1200);
    Producto p85 = new Producto(85, "RETIRO DE  CONTADOR EN POSTE INCLUYE CAJA  CONTADOR Y  PROTECIONES", "UN",79500);
    Producto p86 = new Producto(86, "CONECCION DE EQUIPO  MEDIDA EN  SUBESTACION", "UN",133300);
    Producto p87 = new Producto(87, "CONECCION DE  SECCIONADOR EN SUBESTACION", "UN ",126000);
    Producto p88 = new Producto(88, "CONECCION DE TRASFORMADOR EN SUBESTACION", "UN",174000);
    Producto p89 = new Producto(89, "PRENZADA DE CONETORES EN C  EN  CAJA DE DISTRIBUCION", "UN",5500);
    Producto p90 = new Producto(90, "INSTALACION DE BASE  Y  FOCELDA  ", "UN",43000);
    Producto p91 = new Producto(91, "instalacion de acometida en 3# 8 + 1 #10 ", "ML",3700);
    
    Producto p92 = new Producto(92, "salidas eléctricas provisonales con pvc", "UN",27000);
    Producto p93 = new Producto(93, "salidas eléctricas provisonales con MT", "UN",32000);
    Producto p94 = new Producto(94, "prenzada de borda a terminal", "UN",8500);
    
    
    public  ListaProductos(){
        ProductsList.add(p0);
        ProductsList.add(p1);
        ProductsList.add(p2);
        ProductsList.add(p3);
        ProductsList.add(p4);
        ProductsList.add(p5);
        ProductsList.add(p6);
        ProductsList.add(p7);
        ProductsList.add(p8);
        ProductsList.add(p9);
        ProductsList.add(p10);
        ProductsList.add(p11);
        ProductsList.add(p12);
        ProductsList.add(p13);
        ProductsList.add(p14);
        ProductsList.add(p15);
        ProductsList.add(p16);
        ProductsList.add(p17);
        ProductsList.add(p18);
        ProductsList.add(p19);
        ProductsList.add(p20);
        ProductsList.add(p21);
        ProductsList.add(p22);
        ProductsList.add(p23);
        ProductsList.add(p24);
        ProductsList.add(p25);
        ProductsList.add(p26);
        ProductsList.add(p27);
        ProductsList.add(p28);
        ProductsList.add(p29);
        ProductsList.add(p30);
        ProductsList.add(p31);
        ProductsList.add(p32);
        ProductsList.add(p33);
        ProductsList.add(p34);
        ProductsList.add(p35);
        ProductsList.add(p36);
        ProductsList.add(p37);
        ProductsList.add(p38);
        ProductsList.add(p39);
        ProductsList.add(p40);
        ProductsList.add(p41);
        ProductsList.add(p42);
        ProductsList.add(p43);
        ProductsList.add(p44);
        ProductsList.add(p45);
        ProductsList.add(p46);
        ProductsList.add(p47);
        ProductsList.add(p48);
        ProductsList.add(p49);
        ProductsList.add(p50);
        ProductsList.add(p51);
        ProductsList.add(p52);
        ProductsList.add(p53);
        ProductsList.add(p54);
        ProductsList.add(p55);
        ProductsList.add(p56);
        ProductsList.add(p57);
        ProductsList.add(p58);
        ProductsList.add(p59);
        ProductsList.add(p60);
        ProductsList.add(p61);
        ProductsList.add(p62);
        ProductsList.add(p63);
        ProductsList.add(p64);
        ProductsList.add(p65);
        ProductsList.add(p66);
        ProductsList.add(p67);
        ProductsList.add(p68);
        ProductsList.add(p69);
        ProductsList.add(p70);
        ProductsList.add(p71);
        ProductsList.add(p72);
        ProductsList.add(p73);
        ProductsList.add(p74);
        ProductsList.add(p75);
        ProductsList.add(p76);
        ProductsList.add(p77);
        ProductsList.add(p78);
        ProductsList.add(p79);
        ProductsList.add(p80);
        ProductsList.add(p81);
        ProductsList.add(p82);
        ProductsList.add(p83);
        ProductsList.add(p84);
        ProductsList.add(p85);
        ProductsList.add(p86);
        ProductsList.add(p87);
        ProductsList.add(p88);
        ProductsList.add(p89);
        ProductsList.add(p90);
        ProductsList.add(p91);
        ProductsList.add(p92);
        ProductsList.add(p93);
        ProductsList.add(p94);
    }
    
    public int MostrarCodigo(int x){
       int aux = ProductsList.get(x).obtener_codigo();
       return aux;
    }
    
    public String MostrarDescripcion(int x){
        String aux = ProductsList.get(x).obtener_descrpcion();
        return aux;
    }
    
    public double MostrarValor(int x){
        double aux = ProductsList.get(x).obtener_valor();
        return aux;
    }
}
